exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: debug-statements
        exclude: .dcg_templates/*
      - id: check-executables-have-shebangs

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: .dcg_templates/*

  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        exclude: .dcg_templates/*

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        exclude: .dcg_templates/*
