# Generated by Django 4.1.1 on 2023-04-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0002_remove_product_size_product_cover_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="main_photo",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
