# Generated by Django 4.1.1 on 2023-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0004_product_price_product_price_after_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
