# Generated by Django 4.1.1 on 2023-05-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0005_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="extra_price",
            field=models.IntegerField(default=1),
        ),
    ]
