# Generated by Django 4.1.1 on 2023-07-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0006_product_extra_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_ar",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
