# Generated by Django 4.1.1 on 2023-07-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0007_product_description_ar_product_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfeatures",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productfeatures",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
