# Generated by Django 4.1.1 on 2023-04-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addonsapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectioncontent",
            name="page_section",
        ),
        migrations.RemoveField(
            model_name="sliderpicture",
            name="page_section",
        ),
        migrations.DeleteModel(
            name="PageSection",
        ),
        migrations.DeleteModel(
            name="SectionContent",
        ),
        migrations.DeleteModel(
            name="SliderPicture",
        ),
    ]
