# Generated by Django 4.1.1 on 2023-04-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
