# Generated by Django 4.1.1 on 2023-04-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0003_remove_orderdetails_oder_orderdetails_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_details",
                to="orderapp.order",
            ),
        ),
    ]
