# Generated by Django 4.1.1 on 2023-05-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0006_drafts"),
    ]

    operations = [
        migrations.AddField(
            model_name="drafts",
            name="images",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="drafts",
            name="layouts",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="drafts",
            name="product",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="drafts",
            name="service",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
