# Generated by Django 4.1.1 on 2023-05-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productapp", "0004_product_price_product_price_after_discount"),
        ("servicesapp", "0002_category"),
        ("orderapp", "0007_drafts_images_drafts_layouts_drafts_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drafts",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="productapp.product",
            ),
        ),
        migrations.AlterField(
            model_name="drafts",
            name="service",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="servicesapp.service",
            ),
        ),
    ]
