# Generated by Django 4.1.1 on 2023-05-25 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0009_drafts_quantity_cart_drafts_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drafts",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_drafts",
                to="orderapp.cart",
            ),
        ),
    ]
