# Generated by Django 4.1.1 on 2023-05-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        ("orderapp", "0010_alter_drafts_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.payment",
            ),
        ),
    ]
