# Generated by Django 4.1.1 on 2023-05-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0014_orderdetails_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="pdf",
            field=models.FileField(blank=True, default=None, null=True, upload_to=None),
        ),
    ]
