# Generated by Django 4.1.1 on 2023-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0015_alter_orderdetails_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("preparing", "preparing"),
                    ("delivering", "delivering"),
                    ("delivered", "delivered"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
