# Generated by Django 4.1.1 on 2023-05-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_remove_address_country_remove_address_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
