# Generated by Django 4.1.1 on 2023-05-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_user_is_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
