# Generated by Django 4.1.1 on 2023-05-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="media/"
            ),
        ),
    ]
