# Generated by Django 4.1.1 on 2023-07-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0003_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
