# Generated by Django 4.1.1 on 2022-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificationapp", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="content",
            new_name="description",
        ),
        migrations.AddField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.TextField(),
        ),
    ]
