# Generated by Django 4.1.1 on 2022-12-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificationapp", "0003_rename_content_notification_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="body",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
