# Generated by Django 4.1.1 on 2022-12-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificationapp", "0004_alter_notification_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
