# Generated by Django 4.1.1 on 2022-12-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificationapp", "0006_notification_date_notification_is_action_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_clicked",
            field=models.BooleanField(default=False),
        ),
    ]
